version: "3"
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./app/:/home/app/
    depends_on:
      - db
    restart: on-failure
    
  db:
    image: postgres:10
    env_file: .env
    expose:
      - 5432

# docker exec -it 6c501f83945e psql -U name testdb